### ISSUE TITLE
Changes aren't showing up

### ISSUE THREAD

**Issue by Czar-Ec** [SilvT1/Portfolio#3]
Just noticed that my changes to show your CV (and your own changes) isn't showing up?
You might want to see if its asking for approval, otherwise I might need to have a look through this.

**Comment by SilvT1** [comment]
I can see he changes when I run this locally using ng serve --open but I can't see the changes any other way I thought this needed a CLI command to apply to the other files but haven't found anything like that

**Comment by Czar-Ec** [comment]
I built it with the changes so it should appear, but I'll look at the diffs of the built files

**Comment by Czar-Ec** [comment]
Ayy fixed!
So my "hidden" HTML comment was breaking how intro was being parsed and my code to point to your CV was turned from "/assets..." to "assets..." i.e. removed a slash
